### ISSUE TITLE
How to find the encoding after first LSTM?

### ISSUE THREAD

**Issue by Sucheta-d** [somvirs57/seq2seq_methematic_sum#1]
I would like to extract useful features in the data and for that, I need to know the output of the first LSTM, which is fed into the decoder step. How to do that? Please help.

**Comment by somvirs57** [comment]
Hi Sucheta, 
As I don't have your code, so my only advice is: 
I request you to go through the encoder-decoder model for machine translation at https://github.com/somvirs57/seq2seq_fre_eng_translation  because that model deeply explores the encoder-decoder model and lstms. 

- So we know we get values and two-state values from lstm output. so first, we need to set return state = True in lstm definition to get states along with values. 
en**coder = LSTM(lstm_dim, return_state=True)**  

 - after that, we can go ahead with defining the complete encoder-decoder model as shown in the file. 

- and after training, we create a separate model for getting encoder values:
**encoder_model = Model(encoder_inputs, [encoder_states,encoder_outputs])** 
This will take input of the encoder and output the states as well as outputs of the first encoder lstm.

- we can run this as:
outputs, state_values = encoder_model.predict(input_seq)

and this way you get the required outputs and states of the first encoder... 

Hope I am able to at least direct you in correct path if not answer your question.
